name: "kadlab"

services:
  dns:
    build: ../dns/
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 1s
    networks:
      - kademlia
  
  bootstrap:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      dns:
        condition: service_healthy
    environment:
      DNS: "dns:3000"
      DOMAIN: "boot.se"
    networks:
      - kademlia
    volumes:
      - ./data:/app/data

  node:
    build: .
    stdin_open: true
    tty: true
    environment:
      DNS: "dns:3000"
      BOOTSTRAP: "bootstrap:8080"
    command: >
      sh -c '
        DOMAIN="$${HOSTNAME}.com";
        export DOMAIN;
        exec /app/kademlia-bin
      '
    depends_on:
      - bootstrap
    networks:
      - kademlia
    volumes:
      - ./data:/app/data
    # deploy:
    #   replicas: 49

  

networks:
  kademlia: